### ISSUE TITLE
adb check not processing version

### ISSUE THREAD

**Issue by kerlerm** [dlenski/tetherback#11]
The version check does not process all variants of adb version output correctly. Newer versions of ADB have a second line of output for the version that includes a specific revision (git SHA):

```
Android Debug Bridge version 1.0.32                                                                                                                                                 
Revision 09a0d98bebce-android 
```

Testing the above fails.

Perhaps example code from https://android.googlesource.com/platform/system/core/+/master/adb/test_adb.py#45 will help:

```
    def test_version(self):
        """Get a version number out of the output of adb."""
        lines = subprocess.check_output(['adb', 'version']).splitlines()
        version_line = lines[0]
        self.assertRegexpMatches(
            version_line, r'^Android Debug Bridge version \d+\.\d+\.\d+$')
        if len(lines) == 2:
            # Newer versions of ADB have a second line of output for the
            # version that includes a specific revision (git SHA).
            revision_line = lines[1]
            self.assertRegexpMatches(
                revision_line, r'^Revision [0-9a-f]{12}-android$')

```

**Comment by dlenski** [comment]
Kind of amusing that Google's own approach is to parse the output with a regex :-/. Does this fix it?

**Comment by kerlerm** [comment]
That does the trick. Thanks! 

But the question is still: Do we have to check _both_ sides of the connection for certain version numbers? Can't answer that. :-(
