### ISSUE TITLE
Be more explicit about excluding /data/media*

### ISSUE THREAD

**Issue by Blender3D** [dlenski/tetherback#35]
I lost a bunch of data recently because TWRP excludes `/data/media*` from its backups. The developers of TWRP [don't see this as a serious issue](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/276), but excluding the one thing that I actually care about from my backups is dangerous default behavior.

How do you feel about renaming `--media` to `--include-media` and making the user pick either `--include-media` or `--exclude-media` when doing a TWRP-compatible backup?

**Comment by dlenski** [comment]
Ah, I hadn't thought about that. You're right that it's not a safe default behavior, especially for `tetherback` which isn't limited by storage space on the device itself.

It's probably best to include `/data/media*` by default and add a `--no-media` option (similar naming to `--no-boot`, etc.).

Want to take a crack at a PR to fix that?

**Comment by dgw** [comment]
_silently forks and clones the project to have a little fun making a PR_

I've been meaning to practice with argparse anyway 😀  (and I'm waiting for updates to install on my other machine).
