### ISSUE TITLE
python package issues

### ISSUE THREAD

**Issue by theduffster** [dlenski/tetherback#4]
This was a problem I first encountered when I tried to run the program.

The correct progressbar to install is progressbar2 which is the one which still works with newer versions of python.
Use: `sudo pip install progressbar2`

You also need to install tabulate for this to work.
Use: `sudo pip install tabulate`

I had to install these packages to get this to work and most other users probably will have to as well so I think it might be a good idea to add instructions on installing these packages to the readme.

**Comment by dlenski** [comment]
Thanks, these were already mentioned in [README.md](http://github.com/dlenski/tetherback/blob/head/README.md), but I changed `progressbar` → `progressbar2`.

One of these days I will add a proper `setup.py` so that the dependencies can be installed automatically...
