### ISSUE TITLE
add adbpath as argument

### ISSUE THREAD

**Issue by TobiasHeidlund** [dlenski/tetherback#60]
The program cant seem to find my adb install location is there a way to specify it manualy or could u possibly add it as a argument

**Comment by dlenski** [comment]
Yeah, that would be easy to add.

1. You should add the option here: https://github.com/dlenski/tetherback/blob/HEAD/tetherback/tetherback.py#L31
2. … and then use its output here (in place of `'adb'`): https://github.com/dlenski/tetherback/blob/HEAD/tetherback/tetherback.py#L326

Please submit a PR :)

**Comment by ckrmml** [comment]
this could be closed
